### ISSUE TITLE
Loaded save should be parsed just a single time

### ISSUE THREAD

**Issue by db48x** [foxxbl/shady-search#10]
Instead of making the user select a sector and then click the “Parse” button, parse the file after it is loaded and then prompt the user to select a sector from amongst those found in the save. For bonus points, show the number of shady guys in the sector in another column.

**Comment by foxxbl** [comment]
Hi @db48x, this is a good suggestion, I would need to check the overall parsing time.
There are ~140 sectors, and parsing one sector takes up to 5 seconds on my Ryzen 5600X. Therefore parsing of all sectors will take approx. 10 minutes (but I need to check actual parsing time). Long parsing time would reduce usability and make tool too tedious for use. I will evaluate this, but anything longer than a couple of minutes will be unusable.. Maybe this could be an additional option one can choose. In that case tool would have ability to show number of black marketeers as you propose, and even re-parse button for that sector..

**Comment by db48x** [comment]
That would be a long time to wait. I haven’t actually looked at the code to see how you implement it, but I have no doubt that it could be sped up a bit. After all, the game loads the same file and it doesn’t take 10 minutes. :D

**Comment by foxxbl** [comment]
You are right of course, it shouldn't take so long if tool would parse the whole universe than sector by sector. Thanks for the valuable input, will get back to you..

**Comment by foxxbl** [comment]
@db48x  new 2.0.0 version has been released with the suggested change.
