### ISSUE TITLE
someone posted a save that can’t be opened

### ISSUE THREAD

**Issue by db48x** [foxxbl/shady-search#20]
[vvvvvvvv](https://forum.egosoft.com/memberlist.php?mode=viewprofile&u=595008) uploaded [this save](https://www.dropbox.com/s/5huhrqjbjspdpih/save_001.xml.gz?dl=0) to the Black Marketeer bug report but shady-search cannot open it.

The error message reads “Cannot find translation for sector macro cluster_black_sector01_macro”. I’m not familiar enough with the save file format to know what this error means precisely, but is there a way to make it non–fatal?

**Comment by foxxbl** [comment]
thanks, I will check the issue. In the  mean time, your PR is a good stop-gap measure to allow any sector to be added.
I scanned all game files from version 7.0 unless possibly something was added in 7.10 or this is a modded game.
